<?php

return [
    'ACCURATE_CLIENT_ID' => env('ACCURATE_CLIENT_ID'),
    'ACCURATE_CLIENT_SECRET' => env('ACCURATE_CLIENT_SECRET'),
    'ACCURATE_CALLBACK' => env('ACCURATE_CALLBACK'),
    'ACCURATE_API_ENDPOINT' => env('ACCURATE_API_ENDPOINT')
];
